### ISSUE TITLE
target-dummydiv unable to locate element

### ISSUE THREAD

**Issue by iuriimattos2** [ElHaban3ro/DeeptransTool#1]
I think target-dummydiv is change, try out to locate an element with the CSS selector [id="target-dummydiv"], but it is unable to find the element on the page. 

The error trace:
```
  File "Python311\MyLib\packages\DTT\deepLTranslate.py", line 247, in file_translate
    translate_save = browser.find_element(By.ID, 'target-dummydiv')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Python311\MyLib\packages\selenium\webdriver\remote\webdriver.py", line 856, in find_element
    return self.execute(Command.FIND_ELEMENT, {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Python311\MyLib\packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "Python311\MyLib\packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="target-dummydiv"]"}
  (Session info: headless chrome=114.0.5735.198)
```

I would greatly appreciate any assistance or guidance you could provide in resolving this issue. If there are any additional details or information that would be helpful, please let me know and I will gladly provide them.

Thank you for your time and attention. I look forward to your response. Best regards!

**Comment by a-silliy-sheep** [comment]
yeah, I met the same problem as you

**Comment by ElHaban3ro** [comment]
Hi guys! An apology for not being able to attend to the error. In a few hours I will try to take a closer look at why the behavior is happening and make a commit! I will mark this issue as resolved when it is fixed.

**Comment by ElHaban3ro** [comment]
Problem solved!

https://github.com/ElHaban3ro/DeeptransTool/releases/tag/Release
